server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://locahost:3306/oes?serverTimeZone=Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 147258369asd
  redis:
    # Redis 服务器地址
    host: 127.0.0.1

#统一文件存放路径
oes:
  path: