# spring配置
spring:
  # 设置spring运行环境
  profiles:
    active: @env@
  # 设置App名字
  application:
    name: OnlineExaminationSystem
  # 文件上传下载大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  # 开启循环依赖
  main:
    allow-circular-references: true
  # springMVC配置
  mvc:
    # 解决spring解析路径和swagger冲突问题
    pathmatch:
      matching-strategy: ant_path_matcher
  # Redis 配置
  redis:
    # 连接端口号
    port: 6379
    # 数据库索引（0 - 15）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 10000
    # lettuce 参数
    lettuce:
      pool:
        # 最大连接数(使用负值表示没有限制) 默认为 8
        max-active: 10
        # 最大阻塞等待时间(使用负值表示没有限制) 默认为 -1 ms
        max-wait: -1
        # 最大空闲连接 默认为 8
        max-idle: 5
        # 最小空闲连接 默认为 0
        min-idle: 0

# mybatis-plus配置
mybatis-plus:
  configuration:
    # 开启下划线转驼峰
    map-underscore-to-camel-case: true
    # 指定输出日志类
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl