server:
  port: 8080

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/oes?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 147258369asd
  redis:
    # Redis 服务器地址
    host: 127.0.0.1

#统一文件存放路径
oes:
  path: E:\oes_file\
  picture:
    base: E:\oes_file\picture\
    user-picture: E:\oes_file\picture\user
    exam-picture: E:\oes_file\picture\exam
    banner-picture: E:\oes_file\picture\banner
